spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://140.143.170.96:5432/ai-rag-knowledge
  ai:
    dashscope:
      api-key: sk-84121097193a4d6881d0ce6998fdd988
    ollama:
        base-url: http://140.143.170.96:11434
        chat:
          model: deepseek-r1:1.5b
    vectorstore:
        pgvector:
          dimensions: 1536
          index-type: hnsw
          distance-type: cosine_distance
redis:
  sdk:
    config:
      host: 140.143.170.96
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true



